baseURL = "https://weihanglo.tw"
title = "Weihang Lo"
copyright = "CC BY-NC-SA 4.0"
theme = "PaperMod"
paginate = 1000
enableRobotsTXT = true # generate robots.txt
enableEmoji = true
# Missing translations will default to this content language
defaultContentLanguage = "en"
hasCJKLanguage = true

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"
posts = "/posts/:year/:filename/"

[[menu.main]]
name = "Home"
weight = 10
identifier = "home"
url = "/"

[[menu.main]]
name = "Posts"
weight = 20
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Tags"
weight = 40
identifier = "tags"
url = "/tags/"

[[menu.main]]
name = "About"
weight = 50
identifier = "about"
url = "/about/"

[blackfriday]
hrefTargetBlank = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
ShowReadingTime = true
ShowPostNavLinks = true
showtoc = true
disableSpecial1stPost = true
[params.assets]
disableFingerprinting = true
